[build]
  command = "ng build --configuration=production"
  publish = "dist/my-portfolio-v2/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Environment settings
[build.environment]
  NODE_VERSION = "18"